package_name: clorinde
genshin_id: 10000098
key: clorinde
# icd_groups:
#   - group_name: ICDGroupArlecchinoElementalArt
#     reset_timer: 600
#     ele_app_sequence:
#       [1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
#     damage_sequence: [1, 1, 1, 1, 1]
skill_data_mapping:
  attack: # Normal Attack: Marechaussee Creed
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
      - 3 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
    attack_4:
      - 4 # 4-Hit DMG|{param4:F1P}+{param5:F1P}+{param6:F1P}
      - 5 # 4-Hit DMG|{param4:F1P}+{param5:F1P}+{param6:F1P}
      - 6 # 4-Hit DMG|{param4:F1P}+{param5:F1P}+{param6:F1P}
    attack_5:
      - 9 # 5-Hit DMG|{param9:F1P}
    charge:
      - 10 # Charged Attack DMG|{param10:F1P}
    #     charge_stam:
    #       - 11 # Charged Attack Stamina Cost|{param11:F1}
    collision:
      - 12 # Plunge DMG|{param12:F1P}
    lowPlunge:
      - 13 # Low/High Plunge DMG|{param13:P}/{param14:P}
    highPlunge:
      - 14 # Low/High Plunge DMG|{param13:P}/{param14:P}
  skill: # Hunt the Dark
    skillNA:
      - 0 # Normal/Piercing Shot DMG|{param0:F1P}/{param1:F1P}
    skillEnhancedNA:
      - 1 # Normal/Piercing Shot DMG|{param0:F1P}/{param1:F1P}
    skillBOLGain:
      - 2 # Bond of Life Gained|{param2:F1P} Max HP
    skillLungeNoBOL:
      - 3 # Level 1 Enhanced Thrust DMG|{param3:F1P}
    skillLungeLowBOL:
      - 4 # Level 2 Enhanced Thrust DMG|{param4:F1P}
    skillLungeLowBOLHeal:
      - 5 # Level 2 Enhanced Thrust Healing|{param5:F1P} Current Bond of Life
    skillLungeFullBOL:
      - 6 # Level 3 Enhanced Thrust DMG|{param6:F1P}×3
    skillLungeFullBOLHeal:
      - 7 # Level 3 Enhanced Thrust Healing|{param7:F1P} Current Bond of Life
    healingBOL:
      - 8 # Bond of Life Gained From Healing|{param8:P} Healed Amount
    arkheDamage:
      - 9 # Surging Blade DMG|{param9:F1P}
    arkheCD:
      - 10
    skillStateDuration:
      - 11
    # skillCD:
    #   - 12
  burst: # Last Lightfall
    burstDamage:
      - 0 # Skill DMG|{param0:F1P}×5
    burstBOL:
      - 1 # Bond of Life Obtained|{param1:F1P} Max HP
    # burstCD:
    #   - 3 # CD|{param3:F1}s
#     burstEnergy:
#       - 4 # Energy Cost|{param4:I}
