// Code generated by "pipeline"; DO NOT EDIT.

package linnea

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Linnea, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack: {"travel"},
		action.ActionAim:    {"hold", "travel", "weakspot"},
		action.ActionSkill:  {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Linnea, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: CaptureProtocol - 1-Hit DMG: {0}
			0.589969,
			0.637989,
			0.68601,
			0.754611,
			0.802632,
			0.857513,
			0.932974,
			1.008435,
			1.083896,
			1.166217,
			1.248538,
			1.330859,
			1.413181,
			1.495502,
			1.577823,
		},
		{ // attack: CaptureProtocol - 2-Hit DMG: {1}
			0.511519,
			0.553155,
			0.59479,
			0.654269,
			0.695904,
			0.743488,
			0.808914,
			0.874341,
			0.939768,
			1.011143,
			1.082518,
			1.153893,
			1.225267,
			1.296642,
			1.368017,
		},
		{ // attack: CaptureProtocol - 3-Hit DMG: {2}
			0.816312,
			0.882756,
			0.9492,
			1.04412,
			1.110564,
			1.1865,
			1.290912,
			1.395324,
			1.499736,
			1.61364,
			1.727544,
			1.841448,
			1.955352,
			2.069256,
			2.18316,
		},
	}
	// attack: CaptureProtocol - Aimed Shot: {3}
	aim = []float64{
		0.4386,
		0.4743,
		0.51,
		0.561,
		0.5967,
		0.6375,
		0.6936,
		0.7497,
		0.8058,
		0.867,
		0.9282,
		0.9894,
		1.0506,
		1.1118,
		1.173,
	}
	// attack: CaptureProtocol - Fully-Charged Aimed Shot: {4}
	fullAim = []float64{
		1.24,
		1.333,
		1.426,
		1.55,
		1.643,
		1.736,
		1.86,
		1.984,
		2.108,
		2.232,
		2.356,
		2.48,
		2.635,
		2.79,
		2.945,
	}
	// skill: CountermeasureLumisBattleCry - Lumi Pound-Pound Pummeler DMG: {0} DEF ×2
	skillPound = []float64{
		0.96,
		1.032,
		1.104,
		1.2,
		1.272,
		1.344,
		1.44,
		1.536,
		1.632,
		1.728,
		1.824,
		1.92,
		2.04,
		2.16,
		2.28,
	}
	// skill: CountermeasureLumisBattleCry - Lumi Heavy Overdrive Hammer DMG: {1} DEF
	skillHeavy = []float64{
		1.0,
		1.075,
		1.15,
		1.25,
		1.325,
		1.4,
		1.5,
		1.6,
		1.7,
		1.8,
		1.9,
		2.0,
		2.125,
		2.25,
		2.375,
	}
	// skill: CountermeasureLumisBattleCry - Lumi Million Ton Crush DMG: {2} DEF
	skillMillion = []float64{
		4.0,
		4.3,
		4.6,
		5.0,
		5.3,
		5.6,
		6.0,
		6.4,
		6.8,
		7.2,
		7.6,
		8.0,
		8.5,
		9.0,
		9.5,
	}
	// burst: MemoSurvivalGuideInExtremeConditions - Initial Healing Amount: {1} DEF+{0}
	burstInitialDef = []float64{
		1.6,
		1.72,
		1.84,
		2.0,
		2.12,
		2.24,
		2.4,
		2.56,
		2.72,
		2.88,
		3.04,
		3.2,
		3.4,
		3.6,
		3.8,
	}
	// burst: MemoSurvivalGuideInExtremeConditions - Initial Healing Amount: {1} DEF+{0}
	burstInitialFlat = []float64{
		770.3755,
		847.4238,
		930.8927,
		1020.782,
		1117.093,
		1219.824,
		1328.975,
		1444.548,
		1566.541,
		1694.955,
		1829.789,
		1971.044,
		2118.72,
		2272.816,
		2433.334,
	}
	// burst: MemoSurvivalGuideInExtremeConditions - Continuous Healing: {3} DEF+{2}
	burstTickDef = []float64{
		0.32,
		0.344,
		0.368,
		0.4,
		0.424,
		0.448,
		0.48,
		0.512,
		0.544,
		0.576,
		0.608,
		0.64,
		0.68,
		0.72,
		0.76,
	}
	// burst: MemoSurvivalGuideInExtremeConditions - Continuous Healing: {3} DEF+{2}
	burstTickFlat = []float64{
		154.0751,
		169.4848,
		186.1785,
		204.1565,
		223.4185,
		243.9647,
		265.7951,
		288.9095,
		313.3082,
		338.9909,
		365.9578,
		394.2088,
		423.744,
		454.5633,
		486.6667,
	}
)
