// Code generated by "pipeline"; DO NOT EDIT.

package mitya

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Mitya, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionSkill: {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Mitya, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: ChainReaction - 1-Hit DMG: {0}
			0.587984,
			0.632083,
			0.676182,
			0.73498,
			0.779079,
			0.823178,
			0.881976,
			0.940774,
			0.999573,
			1.058371,
			1.11717,
			1.175968,
			1.249466,
			1.322964,
			1.396462,
		},
		{ // attack: ChainReaction - 2-Hit DMG: {1}
			0.483008,
			0.519234,
			0.555459,
			0.60376,
			0.639986,
			0.676211,
			0.724512,
			0.772813,
			0.821114,
			0.869414,
			0.917715,
			0.966016,
			1.026392,
			1.086768,
			1.147144,
		},
		{ // attack: ChainReaction - 3-Hit DMG: {2}
			0.690224,
			0.741991,
			0.793758,
			0.86278,
			0.914547,
			0.966314,
			1.035336,
			1.104358,
			1.173381,
			1.242403,
			1.311426,
			1.380448,
			1.466726,
			1.553004,
			1.639282,
		},
	}
	// attack: ChainReaction - Charged Attack DMG: {3}
	charge = []float64{
		1.3688,
		1.47146,
		1.57412,
		1.711,
		1.81366,
		1.91632,
		2.0532,
		2.19008,
		2.32696,
		2.46384,
		2.60072,
		2.7376,
		2.9087,
		3.0798,
		3.2509,
	}
	// attack: ChainReaction - Gradient Detonation DMG: {8}
	chargeSpecial = []float64{
		1.53,
		1.64475,
		1.7595,
		1.9125,
		2.02725,
		2.142,
		2.295,
		2.448,
		2.601,
		2.754,
		2.907,
		3.06,
		3.25125,
		3.4425,
		3.63375,
	}
	// attack: ChainReaction - Gradient Detonation Stellar-Conduct DMG: {9} Elemental Mastery
	chargeSSC = []float64{
		2.04,
		2.193,
		2.346,
		2.55,
		2.703,
		2.856,
		3.06,
		3.264,
		3.468,
		3.672,
		3.876,
		4.08,
		4.335,
		4.59,
		4.845,
	}
	// skill: PrincipleVariableDetection - Tap Skill DMG: {0}
	skillPress = []float64{
		0.9072,
		0.97524,
		1.04328,
		1.134,
		1.20204,
		1.27008,
		1.3608,
		1.45152,
		1.54224,
		1.63296,
		1.72368,
		1.8144,
		1.9278,
		2.0412,
		2.1546,
	}
	// skill: PrincipleVariableDetection - Hold Skill DMG: {1}
	skillHold = []float64{
		1.296,
		1.3932,
		1.4904,
		1.62,
		1.7172,
		1.8144,
		1.944,
		2.0736,
		2.2032,
		2.3328,
		2.4624,
		2.592,
		2.754,
		2.916,
		3.078,
	}
	// skill: PrincipleVariableDetection - Steady State Core DMG: {2}
	skillPulse = []float64{
		0.72,
		0.774,
		0.828,
		0.9,
		0.954,
		1.008,
		1.08,
		1.152,
		1.224,
		1.296,
		1.368,
		1.44,
		1.53,
		1.62,
		1.71,
	}
	// skill: PrincipleVariableDetection - Steady State Core Gradient Beacon Consumption DMG: {3} Elemental Mastery
	skillPrismSurge = []float64{
		0.912,
		0.9804,
		1.0488,
		1.14,
		1.2084,
		1.2768,
		1.368,
		1.4592,
		1.5504,
		1.6416,
		1.7328,
		1.824,
		1.938,
		2.052,
		2.166,
	}
	// skill: PrincipleVariableDetection - Steady State Core Detonation DMG: {4}/Beacon
	skillPrismShardPerPrism = []float64{
		1.04,
		1.118,
		1.196,
		1.3,
		1.378,
		1.456,
		1.56,
		1.664,
		1.768,
		1.872,
		1.976,
		2.08,
		2.21,
		2.34,
		2.47,
	}
	// burst: AnalysisGradientTheory - Skill DMG: {0} ATK+{1} Elemental Mastery
	burst = []float64{
		3.336,
		3.5862,
		3.8364,
		4.17,
		4.4202,
		4.6704,
		5.004,
		5.3376,
		5.6712,
		6.0048,
		6.3384,
		6.672,
		7.089,
		7.506,
		7.923,
	}
	// burst: AnalysisGradientTheory - Skill DMG: {0} ATK+{1} Elemental Mastery
	burstEM = []float64{
		6.672,
		7.1724,
		7.6728,
		8.34,
		8.8404,
		9.3408,
		10.008,
		10.6752,
		11.3424,
		12.0096,
		12.6768,
		13.344,
		14.178,
		15.012,
		15.846,
	}
)
