// Code generated by "pipeline"; DO NOT EDIT.

package lohen

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Lohen, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Lohen, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: SpearOfFavoniusBrokenOath - 1-Hit DMG: {0}
			0.539917,
			0.583863,
			0.62781,
			0.690591,
			0.734538,
			0.784763,
			0.853822,
			0.922881,
			0.99194,
			1.067277,
			1.142614,
			1.217951,
			1.293289,
			1.368626,
			1.443963,
		}},
		{{ // attack: SpearOfFavoniusBrokenOath - 2-Hit DMG: {1}
			0.564427,
			0.610368,
			0.65631,
			0.721941,
			0.767883,
			0.820387,
			0.892582,
			0.964776,
			1.03697,
			1.115727,
			1.194484,
			1.273241,
			1.351999,
			1.430756,
			1.509513,
		}},
		{{ // attack: SpearOfFavoniusBrokenOath - 3-Hit DMG: {2}×3
			0.254199,
			0.274889,
			0.29558,
			0.325138,
			0.345829,
			0.369475,
			0.401989,
			0.434503,
			0.467016,
			0.502486,
			0.537956,
			0.573425,
			0.608895,
			0.644364,
			0.679834,
		}},
		{{ // attack: SpearOfFavoniusBrokenOath - 4-Hit DMG: {3}
			0.752259,
			0.81349,
			0.87472,
			0.962192,
			1.023422,
			1.0934,
			1.189619,
			1.285838,
			1.382058,
			1.487024,
			1.59199,
			1.696957,
			1.801923,
			1.90689,
			2.011856,
		}},
		{
			{ // attack: SpearOfFavoniusBrokenOath - 5-Hit DMG: {4}+{5}
				0.368579,
				0.398579,
				0.42858,
				0.471438,
				0.501439,
				0.535725,
				0.582869,
				0.630013,
				0.677156,
				0.728586,
				0.780016,
				0.831445,
				0.882875,
				0.934304,
				0.985734,
			},
			{ // attack: SpearOfFavoniusBrokenOath - 5-Hit DMG: {4}+{5}
				0.552868,
				0.597869,
				0.64287,
				0.707157,
				0.752158,
				0.803588,
				0.874303,
				0.945019,
				1.015735,
				1.092879,
				1.170023,
				1.247168,
				1.324312,
				1.401457,
				1.478601,
			},
		},
	}
	// attack: SpearOfFavoniusBrokenOath - Charged Attack DMG: {6}×2
	charge = []float64{
		0.65876,
		0.71238,
		0.766,
		0.8426,
		0.89622,
		0.9575,
		1.04176,
		1.12602,
		1.21028,
		1.3022,
		1.39412,
		1.48604,
		1.57796,
		1.66988,
		1.7618,
	}
	skillAttack = [][][]float64{
		{{ // skill: UnforeseenStrike - 1-Hit DMG: {0}
			0.809875,
			0.875795,
			0.941715,
			1.035887,
			1.101807,
			1.177144,
			1.280732,
			1.384321,
			1.48791,
			1.600915,
			1.713921,
			1.826927,
			1.939933,
			2.052939,
			2.165944,
		}},
		{{ // skill: UnforeseenStrike - 2-Hit DMG: {1}
			0.84664,
			0.915552,
			0.984465,
			1.082912,
			1.151824,
			1.230581,
			1.338872,
			1.447164,
			1.555455,
			1.67359,
			1.791726,
			1.909862,
			2.027998,
			2.146134,
			2.264269,
		}},
		{{ // skill: UnforeseenStrike - 3-Hit DMG: {2}×3
			0.381298,
			0.412334,
			0.44337,
			0.487707,
			0.518743,
			0.554212,
			0.602983,
			0.651754,
			0.700525,
			0.753729,
			0.806933,
			0.860138,
			0.913342,
			0.966547,
			1.019751,
		}},
		{{ // skill: UnforeseenStrike - 4-Hit DMG: {3}
			1.128389,
			1.220234,
			1.31208,
			1.443288,
			1.535134,
			1.6401,
			1.784429,
			1.928758,
			2.073086,
			2.230536,
			2.387986,
			2.545435,
			2.702885,
			2.860334,
			3.017784,
		}},
		{
			{ // skill: UnforeseenStrike - 5-Hit DMG: {4}+{5}
				0.552868,
				0.597869,
				0.64287,
				0.707157,
				0.752158,
				0.803588,
				0.874303,
				0.945019,
				1.015735,
				1.092879,
				1.170023,
				1.247168,
				1.324312,
				1.401457,
				1.478601,
			},
			{ // skill: UnforeseenStrike - 5-Hit DMG: {4}+{5}
				0.829302,
				0.896804,
				0.964305,
				1.060736,
				1.128237,
				1.205381,
				1.311455,
				1.417528,
				1.523602,
				1.639319,
				1.755035,
				1.870752,
				1.986468,
				2.102185,
				2.217901,
			},
		},
	}
	// skill: UnforeseenStrike - Charged Attack DMG: {6}×2
	skillCharge = []float64{
		0.98814,
		1.06857,
		1.149,
		1.2639,
		1.34433,
		1.43625,
		1.56264,
		1.68903,
		1.81542,
		1.9533,
		2.09118,
		2.22906,
		2.36694,
		2.50482,
		2.6427,
	}
	// skill: UnforeseenStrike - Etched Into Bone and Soul DMG: {16}×4
	skillPierce = []float64{
		0.6,
		0.645,
		0.69,
		0.75,
		0.795,
		0.84,
		0.9,
		0.96,
		1.02,
		1.08,
		1.14,
		1.2,
		1.275,
		1.35,
		1.425,
	}
	// burst: ManifestJudgment - Skill DMG: {0}×6
	burst = []float64{
		1.188,
		1.2771,
		1.3662,
		1.485,
		1.5741,
		1.6632,
		1.782,
		1.9008,
		2.0196,
		2.1384,
		2.2572,
		2.376,
		2.5245,
		2.673,
		2.8215,
	}
)
